version: '3.8'

services:
  redis:
    restart: unless-stopped
    image: redis
    ports:
      - 6379:6379

  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    entrypoint: /app/docker/app/server-entrypoint.sh
    ports:
      - 8080:8080
    environment:
      POSTGRES_DB: app
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      CELERY_HOST: redis
      CELERY_PORT: 6379
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_INITDB_DATABASE: lolanalytics
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_ROOT_USERNAME: admin
    depends_on:
      - db
      - redis

  worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    entrypoint: /app/docker/app/worker-entrypoint.sh
    environment:
      POSTGRES_DB: app
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      CELERY_HOST: redis
      CELERY_PORT: 6379
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_INITDB_DATABASE: lolanalytics
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_ROOT_USERNAME: admin
    depends_on:
      - server
      - redis
      - db
    
  front-end:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/front-end/Dockerfile
    entrypoint: /app/docker/front-end/front-entrypoint.sh
    volumes:
      - front-end_static:/app/assets/
      - front-end_nuxt:/app/.nuxt/
    ports:
      - 3000:3000
    depends_on:
      - server

  db:
    restart: unless-stopped
    image: postgres:14-alpine
    volumes:
      - postgres_lol_analytics:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: app
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
  
  mongodb:
    restart: unless-stopped
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: lolanalytics


volumes:
  postgres_lol_analytics: {}
  front-end_static: {}
  front-end_nuxt: {}
  mongodb_data: {}