version: '3.8'

services:
  db:
    restart: unless-stopped
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/LolAnalytics/Dockerfile
    ports:
      - 8000:8000
    environment:
      DATABASE: app
    depends_on:
      - db

volumes:
  postgres_data: {}