# config.py

POSTGRES_USER = ''
POSTGRES_PASSWORD = ''
POSTGRES_DB = ''
POSTGRES_HOST = 'localhost'
POSTGRES_PORT = '5432'

DATABASE_URL = f'postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}'
